config/blog/urls.py
from django.urls import path, include, re_path
from .views import home, detail, category

app_name = "blog"
urlpatterns = [
    path('', home, name="home"),
    path('page/<int:page>', home, name="home"),
    path('article/<slug:slug>', detail, name="detail"),
    path('category/<slug:slug>', category, name="category"),
    path('category/<slug:slug>/page/<int:page>', category, name="category"),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

config/blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from extensions.utils import jalali_converter

# my managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status="p")

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


# Create your models here.

class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name="زیر دسته")
    title = models.CharField(max_length=200, verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length=100, unique=True, allow_unicode=True, verbose_name="لینک کوتاه")
    status = models.BooleanField(default=False, verbose_name='آیا نمایش داده شود ؟')
    position = models.IntegerField(verbose_name="پوزیشن")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ["parent__id", "position"]

    def __str__(self):
        return self.title

    objects = CategoryManager()

class Article(models.Model):
    STATUS_CHOICE = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده')
    )
    title = models.CharField(max_length=200, verbose_name="عنوان")
    slug = models.SlugField(max_length=100, unique=True, allow_unicode=True, verbose_name="لینک کوتاه")
    category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
    description = models.TextField(verbose_name="متن وبلاگ")
    thumbnail = models.ImageField(upload_to="images", verbose_name="عکس")
    publish = models.DateTimeField(default=timezone.now, verbose_name="زمان و تاریخ انتشار")
    created = models.DateTimeField(auto_now_add=True, verbose_name="زمان و تاریخ ساخت")
    updated = models.DateTimeField(auto_now=True, verbose_name="زمان و تاریخ آپدیت")
    status = models.CharField(max_length=1, choices=STATUS_CHOICE, default='d', verbose_name="وضعیت انتشار")

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ["-publish"]

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)

    jpublish.short_description = "زمان انتشار"

    def category_published(self):
        return self.category.filter(status=True)

    def thumbnail_tag(self):
        return format_html("<img width=100 height=75 style='border-radius:5px;' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description = "تصویر"
    objects = ArticleManager()

config/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from django.core.paginator import Paginator

from django.views.generic import ListView

# Create your views here.

#########################################################################

def home(request, page=1):
    articles_list = Article.objects.filter(status="p")
    paginator = Paginator(articles_list, 2)
    articles = paginator.get_page(page)
    context = {
        "articles": articles,
    }

    return render(request, "blog/index.html", context)


# class ArticleList(ListView):
#     queryset = Article.objects.filter(status="p")

#########################################################################

def detail(request, slug):
    context = {
        "article": get_object_or_404(Article, slug=slug, status="p"),
    }

    return render(request, "blog/post.html", context)

def category(request, slug, page=1):
    category = get_object_or_404(Category, slug=slug, status=True)
    articles_list = category.articles.published()
    paginator = Paginator(articles_list, 2)
    articles = paginator.get_page(page)
    context = {
        "articles": articles,
        "category": category
    }

    return render(request, "blog/category.html", context)

config/blog/templates/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>وحید زارع | {% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:home' %}">{% title %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    منو
                    <i class="fas fa-bars"></i>
                </button>
                {% category_navbar %}
            </div>
        </nav>

        {% block content %}

        {% endblock %}

         <!-- Footer-->
         <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

config/blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

config/blog/templates/blog/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}خانه {% endblock %}
        
{% block content %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/blog/assets/img/home-bg.jpg');">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>وحید زارع</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <h3 class="alert alert-primary text-center">دسته بندی : {{category.title}}</h3>
                    {% for article in articles %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:detail' article.slug %}">
                            <h2 class="post-title">{{article.title}}</h2>
                            <h3 class="post-subtitle">{{article.description|truncatewords:30}}</h3>
                        </a>
                        <p class="post-meta">
                            ارسال شده توسط
                            <a href="#!">وحید زارع</a>
                            در {{article.jpublish}}
                        </p>
                        <div>
                            {% for cat in article.category_published.all %}
                                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <hr class="my-4" />
                    <!-- Divider-->
                    {% empty %}
                        <div class="post-preview">
                            <p class="post-meta">
                                در حال حاضر پستی وجود ندارد
                            </p>
                        </div>
                    
                    
                    {% endfor %}
                    <!-- Pager-->
                    {% if articles %}
                        {% if articles.has_next %}
                        <div class="d-flex justify-content-end mb-4 pager-botton"><a class="btn btn-primary text-uppercase" href="{% url 'blog:category' category.slug articles.next_page_number %}">پست های قدیمی &larr;</a></div>
                        {% endif %}
                        {% if articles.has_previous %}
                        <div class="d-flex justify-content-end mb-4 pager-botton" style="margin-left: 5px;"><a class="btn btn-primary text-uppercase" href="{% url 'blog:category' category.slug articles.previous_page_number %}">پست های جدید &rarr;</a></div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
       
{% endblock %}

config/blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}خانه {% endblock %}
        
{% block content %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/blog/assets/img/home-bg.jpg');">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>وحید زارع</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for article in articles %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:detail' article.slug %}">
                            <h2 class="post-title">{{article.title}}</h2>
                            <h3 class="post-subtitle">{{article.description|truncatewords:30}}</h3>
                        </a>
                        <p class="post-meta">
                            ارسال شده توسط
                            <a href="#!">وحید زارع</a>
                            در {{article.jpublish}}
                        </p>
                        <div>
                            {% for cat in article.category_published.all %}
                                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <hr class="my-4" />
                    <!-- Divider-->
                    {% empty %}
                        <div class="post-preview">
                            <p class="post-meta">
                                در حال حاضر پستی وجود ندارد
                            </p>
                        </div>
                    
                    
                    {% endfor %}
                    <!-- Pager-->
                    {% if articles %}
                        {% if articles.has_next %}
                        <div class="d-flex justify-content-end mb-4 pager-botton"><a class="btn btn-primary text-uppercase" href="{% url 'blog:home' articles.next_page_number %}">پست های قدیمی &larr;</a></div>
                        {% endif %}
                        {% if articles.has_previous %}
                        <div class="d-flex justify-content-end mb-4 pager-botton" style="margin-left: 5px;"><a class="btn btn-primary text-uppercase" href="{% url 'blog:home' articles.previous_page_number %}">پست های جدید &rarr;</a></div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
       
{% endblock %}

config/blog/templates/blog/partials/category_loop.html
<ul class="navbar-nav ms-auto py-4 py-lg-0">
    {% for cat in cat.children.active %}
    <li class="nav-item">
        <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
        {% if cat.children.active %}
            {% include "blog/partials/category_loop.html" %}
        {% endif %}
    </li>
    {% endfor %}
</ul>

config/blog/templates/blog/partials/category_navbar.html
<div class="collapse navbar-collapse  nav" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item">
            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:home' %}">خانه</a>
        </li>
        {% for cat in categores %}
            {% if cat.parent == None %}
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
                    {% if cat.children.active %}
                        {% include "blog/partials/category_loop.html" %}
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}

    </ul>
</div>

config/blog/templates/blog/post.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{article.slug}}{% endblock %}

{% block content %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({{article.thumbnail.url}})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{article.title}}</h1>
                            <time>{{article.jpublish}}</time>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        {% if article %}
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7"  style="text-align: justify; line-height: 35px;">
                        <p>{{article.description|linebreaks}}</p>
                        <span class="meta">
                            Posted by
                            <a href="#!">Start Bootstrap</a>
                        </span>

                    </div>
                </div>
            </div>
        </article>
        {% endif %}
{% endblock %}